. $PSScriptRoot/Graph-Rest.ps1
. $PSScriptRoot/Graph-ListApplications.ps1
. $PSScriptRoot/Graph-CreateApplication.ps1
. $PSScriptRoot/Graph-ListSpn.ps1
. $PSScriptRoot/Graph-CreateSpn.ps1
. $PSScriptRoot/Graph-AppAddPassword.ps1
. $PSScriptRoot/Graph-AppRemovePassword.ps1
. $PSScriptRoot/Graph-DeleteApplication.ps1
. $PSScriptRoot/Graph-CreateRole.ps1
. $PSScriptRoot/Graph-GetApplication.ps1
. $PSScriptRoot/Graph-GetSpn.ps1
