-- SPETLR.CONFIGURATOR key: Table1
CREATE TABLE IF NOT EXISTS SomeTable(
a int
)
USING DELTA;

-- SPETLR.CONFIGURATOR key: Table2
CREATE TABLE IF NOT EXISTS AnotherTable(
a int,
b string
)
USING DELTA
LOCATION '/{MNT}/foo/bar';

-- SPETLR.CONFIGURATOR key: Table3
CREATE TABLE IF NOT EXISTS rectangles
(
  id BIGINT GENERATED ALWAYS AS IDENTITY,
  a INT,
  b INT,
  area INT GENERATED ALWAYS AS (a * b)
);
