
# This pipeline can be runned if the SPNs needs to be destroyed
# In this way, it is easier to clean up the SPNs, instead of manually removing them in the portal
name: Spn-Cleanup

on:
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    concurrency:
      group: azure-integration
      cancel-in-progress: true

    steps:

      - name: Log in to azure
        shell: pwsh
        run: |
          az login --service-principal `
            -u ${{ secrets.SPN_CLIENT_ID }} `
            -p ${{ secrets.SPN_CLIENT_SECRET }} `
            --tenant ${{ secrets.SPN_TENANT_ID }}

      - name: Install Databricks CLI
        shell: bash
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - uses: actions/checkout@v4

      - name: Work in databricks
        shell: pwsh
        run: |
          $account = "${{ secrets.DATABRICKS_ACCOUNT_ID }}"
          databricks auth login --host "https://accounts.azuredatabricks.net" --account-id $account
          databricks account service-principals list
